services:
  wander-mark-client:
    image: ${REGISTRY:-docker.io}/injurka/wander-mark-client:${V_CLIENT:-latest}
    restart: unless-stopped
    volumes:
      - ./configs:/usr/share/nginx/html/configs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - trip-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-client.rule=Host(`wander-mark.trip-scheduler.ru`)"
      - "traefik.http.routers.wander-client.entrypoints=websecure"
      - "traefik.http.routers.wander-client.tls.certresolver=letsencrypt"
      - "traefik.http.services.wander-client.loadbalancer.server.port=3333"
      - "traefik.docker.network=trip-net"

  wander-mark-server:
    image: ${REGISTRY:-docker.io}/injurka/wander-mark-server:${V_SERVER:-latest}
    restart: unless-stopped
    environment:
      PORT: "4444"
      FS_BASE_PATH: /data
    volumes:
      - ${VAULT_PATH:-./vault}:/data:ro
    networks:
      - trip-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-server.rule=Host(`wander-api.trip-scheduler.ru`)"
      - "traefik.http.routers.wander-server.entrypoints=websecure"
      - "traefik.http.routers.wander-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.wander-server.loadbalancer.server.port=4444"
      - "traefik.docker.network=trip-net"

networks:
  trip-net:
    external: true
    name: trip-net
