services:
  wander-mark-client:
    image: ${REGISTRY:-docker.io}/injurka/wander-mark-client:${V_CLIENT:-latest}
    restart: unless-stopped
    ports:
      - "3333:3333"
    depends_on:
      - wander-mark-server
    networks:
      - wander-mark

  wander-mark-server:
    image: ${REGISTRY:-docker.io}/injurka/wander-mark-server:${V_SERVER:-latest}
    restart: unless-stopped
    environment:
      PORT: "8080"
      FS_BASE_PATH: /data
    volumes:
      - ${VAULT_PATH:-./vault}:/data:ro
    ports:
      - "4444:8080"
    networks:
      - wander-mark

networks:
  wander-mark:
    driver: bridge
